### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by mougrim** [mattdesl/word-wrapper#4]
Hi!
In readme link http://github.com/mattdesl/word-wrapper/blob/master/LICENSE.md is 404.
Could you add LICENSE.md?

**Comment by mattdesl** [comment]
Hey, will accept a PR using my other repos as a template
https://github.com/mattdesl/canvas-sketch/blob/master/LICENSE.md

Thanks

**Comment by mougrim** [comment]
@mattdesl, #5
